apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: path-provide
  name: path-provide
  namespace: default
spec:
  replicas: 2 #CHANGE
  minReadySeconds: 45
  selector:
    matchLabels:
      app: path-provide
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: path-provide
    spec:
      containers:
      - image: pratik502/path-provide:0.0.1 #CHANGE
        imagePullPolicy: IfNotPresent
        name: path-provide
        env:
#          - name: CURRENCY_EXCHANGE_URI
#            value: http://currency-exchange
#          - name: SPRING_PROFILES_ACTIVE
#            value: kubernetes
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: path-provide
  name: path-provide
  namespace: default
spec:
  ports:
  - # nodePort: 30701 #CHANGE
    port: 8900 #CHANGE
    protocol: TCP
    targetPort: 8900 #CHANGE
  selector:
    app: path-provide
  sessionAffinity: None #CHANGE
  type: LoadBalancer  #try value -NodePort for ingress